language: node_js
node_js: node

before_script: npm run build

before_deploy: tar czf server-configs-test.tar.gz unit/* certs/* fixtures/* README.md LICENSE.txt

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: server-configs-test.tar.gz
  skip_cleanup: true
  on:
    tags: true
