language: node_js
node_js: node

before_script: npm run build

before_deploy: tar czf server-configs-test.tar.gz lib certs fixtures README.md LICENSE.txt

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
    # secure: "itatOgspOE49LX1fczgut51/3AGiCE7ueMeUHdGseB7cWfyFlJ2eUozspXBfbmWtEls8Y97/V1Q8vZty/WXJ2Q3CdxjK8TBBhVycRgK5Qp03eG/yFy/G5hXN1mGil4KwIwqHVYAQvCVcuDv0Ek4V+PEfNp8KGkRILxP2a6kRjgw="
  file: server-configs-test.tar.gz
  skip_cleanup: true
  on:
    tags: true
