language: node_js
node_js: node

env:
  - K6_VERSION="0.24.0"

before_install:
  - curl -sSL "https://github.com/loadimpact/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux64.tar.gz" | tar -xz
  - mv "k6-v${K6_VERSION}-linux64/k6" bin/k6

before_script: npm run build

script:
  - npm run lint
  - ./bin/k6 inspect lib/index.js

before_deploy: tar czf server-configs-test.tar.gz lib certs fixtures bin/k6 README.md LICENSE.txt

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: server-configs-test.tar.gz
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - node_modules
