name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        k6-version: [0.25.1]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          curl -sSL "https://github.com/loadimpact/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux64.tar.gz" | tar -xz
          mv "k6-v${K6_VERSION}-linux64/k6" bin/k6
        env:
          K6_VERSION: ${{ matrix.k6-version }}
      - run: npm ci
      - run: npm run build --if-present

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      - name: Pack
        run: tar czf server-configs-test.tar.gz lib certs fixtures bin/k6 README.md LICENSE.txt
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./server-configs-test.tar.gz
          asset_name: server-configs-test.tar.gz
          asset_content_type: application/gzip
